# Generated by Django 2.0.3 on 2019-08-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190831_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_accepted',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('Accepted', 'Preparing your order'), ('Ready', 'Order ready'), ('Completed', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
