# Generated by Django 2.0.3 on 2019-08-31 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190831_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzaorder',
            name='priced_pizza',
        ),
        migrations.RemoveField(
            model_name='pizzaorder',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='suborder',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='suborder',
            name='priced_sub',
        ),
        migrations.DeleteModel(
            name='PizzaOrder',
        ),
        migrations.DeleteModel(
            name='SubOrder',
        ),
    ]
