# Generated by Django 2.0.3 on 2019-09-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190831_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
