# Generated by Django 2.0.3 on 2019-09-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190904_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
