# Generated by Django 2.0.3 on 2019-09-05 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190904_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='basket',
            name='items',
        ),
        migrations.AddField(
            model_name='basket',
            name='items',
            field=models.ManyToManyField(through='orders.BasketOrderItem', to='orders.OrderItem'),
        ),
        migrations.AddField(
            model_name='basketorderitem',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Basket'),
        ),
        migrations.AddField(
            model_name='basketorderitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderItem'),
        ),
    ]
