# Generated by Django 2.0.3 on 2019-09-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20190913_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=8.95, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Processing your order', 'Processing'), ('Preparing your order', 'Preparing'), ('Your order is ready!', 'Ready'), ('Completed', 'Completed')], default='Processing', max_length=20),
        ),
    ]
