# Generated by Django 2.0.3 on 2019-09-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Processing your order', 'Processing'), ('Preparing your order', 'Preparing'), ('Your order is ready!', 'Ready'), ('Completed', 'Completed')], default='Processing your order', max_length=20),
        ),
    ]
